GET http://localhost:8080/applications

###!SECTION

GET http://localhost:8080/applications/635120d4e6adc00843c98db0

###!SECTION

POST http://localhost:8080/applications 
content-Type: application/json

{
  "userID": "634f2bdebda1dc6050780bfb",
  "jobTitle": "Frontend Web-Developer",       
  "company": {
    "companyName": "Microsoft",
    "contactPerson": { 
    "fullName": "Bill Gates",
    "gender": "m"
    },
    "address": {
      "postCode": "10001",
      "street": "Main Street",
      "city": "New York",
      "email": "google@gmail.com",
      "phone": "123456789",
      "website": "www.facebook.com"
    }
  },
  "motivation": {
    "motName": "Microsoft Motivation",
    "motURL": "../motivations/microsoft_motivation.pdf"
  },
  "resumeID": "635037ec80117605673ac6cf",
  "certificates": {"certID": "6350377380117605673ac6c7"}      
}

###!SECTION

DELETE http://localhost:8080/applications/:id