GET http://localhost:8080/users

###!SECTION
GET http://localhost:8080/users/634d370118d69e82244c6e73/address

###!SECTION

POST http://localhost:8080/users
content-Type: application/json

{
    "firstName": "Mia",
    "lastName": "Müller",
    "address": {
        "postCode": "55564",
        "street": "CloudsevenStr. 7",
        "city": "Wolkenkuckucksheim",
        "email": "m.mueller@gmail.com",
        "phone": ["+49 0123 456 789"]
    },
    "certificates": [{
        "certName": "JavaScript",
        "certURL": "../certificates/javaScript.pdf"
    }],
    "resumes": [{
        "resName": "Lebenslauf Web-Entwickler",
        "resURL": "../resumes/lebenslauf1.pdf"
    }]
  
}

###!SECTION

###!SECTION
PUT http://localhost:8080/users/634f2bdebda1dc6050780bfb
content-Type: application/json

{
    "certificates": [{
        "certName": "PHP-Grundlagen",
        "certURL": "../certificates/php-basics.pdf"
    }],
    "resumes": [{
        "resName": "Lebenslauf Frontend-Entwickler",
        "resURL": "../resumes/Lebenslauf5.pdf"
    }], 
}

###!SECTION
DELETE http://localhost:8080/users/634f2aca560b64d385cbba8b

###!SECTION
GET http://localhost:8080/users/634f2ee1eb1d278628784f72/certificates
