GET http://localhost:8080/users

###!SECTION


GET http://localhost:8080/users/634f2bdebda1dc6050780bfb


###!SECTION

POST http://localhost:8080/users
content-Type: application/json

{
    "firstName": "Hansi",
    "lastName": "Mayer",
    "address": {
        "postCode": "55564",
        "street": "Cloudeleven Str. 11",
        "city": "Wolkenkuckucksheim",
        "email": "m.mueller@gmail.com",
        "phone": ["+49 555 555 555"]
    },
    "certificates": [{
        "certName": "JavaScript",
        "certURL": "../certificates/javaScript.pdf"
    }],
    "resumes": [{
        "resName": "Lebenslauf Web-Entwickler",
        "resURL": "../resumes/lebenslauf1.pdf"
    }]
  
}

###!SECTION

###!SECTION
PUT http://localhost:8080/users/635017c86ef1c4e02a92f367
content-Type: application/json

{
    "firstName": "Hansi",
    "lastName": "Mayer",
    "address": {
        "postCode": "55564",
        "street": "Cloudeleven Str. 11",
        "city": "Oberammergau",
        "email": "m.mueller@gmail.com",
        "phone": "+49 555 555 555"
    },
    "certificates": [{
        "name": "PHP-Zeugnis",
        "URL": "../certificates/javaScript.pdf"
    }],
    "resumes": [{
        "name": "Lebenslauf 5 Web-Entwickler",
        "URL": "../resumes/lebenslauf1.pdf"
    }]
  
}

###!SECTION

DELETE http://localhost:8080/users/635017c86ef1c4e02a92f367


###!SECTION CREATE USER-Documents

POST http://localhost:8080/users/634f2bdebda1dc6050780bfb/certificates
content-Type: application/json

{
    "certName": "Java-Zertifikat",
    "certURL": "../certificates/java.pdf"
}

###!SECTION

POST http://localhost:8080/users/634f2e74eb1d278628784f63/resumes
content-Type: application/json

{
    "resName": "Lebenslauf 1 Junior Web-Entwickler",
    "resURL": "../resumes/lebenslauf1.pdf"
}

###!SECTION
POST http://localhost:8080/users/634f2e74eb1d278628784f63/certificates
content-Type: application/json

{
    "certName": "PHP-Zeugnis",
    "certURL": "../certificates/php.pdf"
}

###!SECTION

GET http://localhost:8080/users/634f2bdebda1dc6050780bfb/certificates

###!SECTION
GET http://localhost:8080/users/634f2bdebda1dc6050780bfb/resumes

###!SECTION

GET http://localhost:8080/users/634f2bdebda1dc6050780bfb/certificates/6350377380117605673ac6c7

###!SECTION

DELETE http://localhost:8080/users/634f2e74eb1d278628784f63/certificates/634f2e74eb1d278628784f64

###!SECTION

DELETE http://localhost:8080/users/634f2e74eb1d278628784f63/resumes/634f2e74eb1d278628784f65

###!SECTION
PUT http://localhost:8080/users/634f2bdebda1dc6050780bfb/certificates/6350377380117605673ac6c7
content-Type: application/json

{
    "certName": "JavaScript-Zertifikat",
    "certURL": "../certificates/javascript.pdf"
}